### ISSUE TITLE
TBoehm/Bitcoin-for-Dummies

### ISSUE THREAD

**Issue by alexandrz** [TBoehm/TBSEngine#1]
Hello,

Someone sent money to one of your projects which has been deleted. Where can I refund it to?

https://tip4commit.com/github/TBoehm/Bitcoin-for-Dummies

**Comment by TBoehm** [comment]
@alexandrz please forward it to https://tip4commit.com/github/OpenBazaar/OpenBazaar - I like the project ;). Also can you delete https://tip4commit.com/github/TBoehm/Bitcoin-for-Dummies for me?

**Comment by alexandrz** [comment]
Done. Thank you!
